language: python

python:
  - "2.7"

script: make test

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

jobs:
  include:
    - stage: wheels
      name: Wheels for Linux
      os: linux
      language: python
      python:
        - "3.6"

      install:
        - pip install --upgrade pip setuptools
        - pip install cython cibuildwheel==1.12.0

      script:
        - cibuildwheel --output-dir wheelhouse

      env:
        - CIBW_BEFORE_BUILD='pip install cython'
      deploy:
        name: Linux
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: wheelhouse/*
        skip_cleanup: true
        draft: true
        prerelease: true
        overwrite: true
        on:
          tags: true

    - stage: wheels
      name: Wheels for Linux AArch64
      os: linux
      arch: arm64
      language: python
      python:
        - "3.6"

      install:
        - pip install --upgrade pip setuptools
        - pip install cython cibuildwheel==1.12.0

      script:
        - cibuildwheel --output-dir wheelhouse

      env:
        - CIBW_BEFORE_BUILD='pip install cython'
      deploy:
        name: Linux
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: wheelhouse/*
        skip_cleanup: true
        draft: true
        prerelease: true
        overwrite: true
        on:
          tags: true

    - stage: wheels
      name: Wheels for OS X
      os: osx
      language: generic

      install:
        - pip install --upgrade pip setuptools
        - pip install cython cibuildwheel==1.1.0

      script:
        - cibuildwheel --output-dir wheelhouse

      env:
        - CIBW_SKIP='cp27-* cp35-*'
        - CIBW_BEFORE_BUILD='pip install cython'
      deploy:
        name: Mac OS X
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: wheelhouse/*
        skip_cleanup: true
        draft: true
        prerelease: true
        overwrite: true
        on:
          tags: true

    - stage: wheels
      name: Wheels for Windows Python 3.[56789]
      os: windows
      language: shell

      install:
        - choco install python3 --version 3.6.8 --sidebyside -y --forcex86 --force --params "/InstallDir:C:\Python36"
      script:
        - C:/Python36/python -m pip install cibuildwheel==1.12.0
        - C:/Python36/python -m cibuildwheel --platform windows --output-dir wheelhouse

      env:
        - CIBW_BUILD='cp3[56789]-*'
        - CIBW_BEFORE_BUILD='python -m pip install cython'
      deploy:
        name: Windows Python 3.[56789]
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: wheelhouse/*
        skip_cleanup: true
        draft: true
        prerelease: true
        overwrite: true
        on:
          tags: true
